In [1]:
import numpy as np
lista1 = [0,1,2,3,4,5,6,7,8,9]

In [2]:
array1 = np.array(lista1)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(np.arange(2,10,2))

[2 4 6 8]


In [6]:
print(np.linspace(1,10,10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [18]:
arrayZero = np.zeros((4,4))
print(arrayZero)
type(arrayZero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


numpy.ndarray

In [14]:
print(np.ones((5,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
lista = np.ones(5)
type(lista)

numpy.ndarray

In [19]:
fullShape = np.full(shape=(3,2), fill_value=8)
print(fullShape)

[[8 8]
 [8 8]
 [8 8]]


In [20]:
base = np.linspace(2,6,4)
print(base)

[2.         3.33333333 4.66666667 6.        ]


In [24]:
g = 5
basePi = np.full_like(base, np.pi)
print(basePi)

[3.14159265 3.14159265 3.14159265 3.14159265]


In [26]:
arrayrando = np.random.rand(4,4)
print(arrayrando)

[[0.63554385 0.01263133 0.11002936 0.05216091]
 [0.47075734 0.88506843 0.56441517 0.30426766]
 [0.07388565 0.11395539 0.45172511 0.26093595]
 [0.07890174 0.37439844 0.74526964 0.95097033]]


In [27]:
arrayLowHigh = np.random.uniform(2,5,4)
print(arrayLowHigh)

[2.3197331  4.24362736 4.35665247 2.73848088]


In [30]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [36]:
b = np.reshape(a,[2,5,2])
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])